package com.ireadygo.app.gamelauncher.appstore.install;

public interface InstallMessage {

	String PACKAGE_NOT_FOUND  = "PACKAGE_NOT_FOUND";
	String PACKAGE_UNREADABLE = "PACKAGE_UNREADABLE";

	String INSTALL_SILENTLY_NOT_COMPATIBLE = "INSTALL_SILENTLY_NOT_COMPATIBLE";
	String INVALID_APK                     = "INVALID_APK";
	String INSUFFICIENT_STORAGE            = "INSUFFICIENT_STORAGE";
	String INCONSISTENT_CERTIFICATES       = "INCONSISTENT_CERTIFICATES";
	String UNKNOW_APK_INSTALL_ERROR        = "UNKNOW_APK_INSTALL_ERROR";
	String INSTALL_PARSE_FAILED_NO_CERTIFICATES        = "INSTALL_PARSE_FAILED_NO_CERTIFICATES";

	String ERROR_ZIP_PACKAGE          = "ERROR_ZIP_PACKAGE";
	String STORAGE_SYSTEM_ERROR       = "STORAGE_SYSTEM_ERROR";
	String EXTERNAL_STORAGE_UNMOUNTED = "STORAGE_SYSTEM_ERROR";
	String ILLEGAL_APK_WITH_DATA      = "ILLEGAL_APK_WITH_DATA";

	String UNINSTALL_FAILED_INVALID_PACKAGE      = "UNINSTALL_FAILED_INVALID_PACKAGE";
	String UNINSTALL_FAILED_INTERNAL_ERROR      = "UNINSTALL_FAILED_INTERNAL_ERROR";
	String UNINSTALL_FAILED_PERMISSION_DENIED      = "UNINSTALL_FAILED_PERMISSION_DENIED";
}
